# name: README build

# on:
#   schedule:
#     - cron: '0 * * * *'
#   workflow_dispatch:

# jobs:
#   update:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout to Main branch
#       uses: actions/checkout@v2
#     - name: Setup Node
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12'
#     - name: Install packages
#       run: npm install
#     - name: Generate README
#       run: node index
#     - name: Test update to repo
#       run: |

#         git config --global user.name "Aditya Bisoi"
#         git config --global user.email "adityabisoi1999@gmail.com"

#         git add -A
#         git commit -m "Generate latest README"
#         git push -f
